name = "wzz-website"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "wzz-db"
database_id = "392def01-1a9b-481c-8768-146b49b1bee2"

[env.production.vars]
JWT_SECRET = "ReplaceWith32BytesRandomString"
